//
//  RegisterInteractor.swift
//  Capo
//
//  Created by Артем Валиев on 12/12/2018.
//  Copyright (c) 2018 Артем Валиев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterBusinessLogic
{
    func registerUser(request: Register.CreateUser.Request)
}

protocol RegisterDataStore
{
    //var name: String { get set }
}

class RegisterInteractor: RegisterBusinessLogic, RegisterDataStore
{
    var presenter: RegisterPresentationLogic?
    var worker: RegisterWorker?
    
    // MARK: Do something
    
    func registerUser(request: Register.CreateUser.Request) {
        let mut = RegisterMutation(name: request.name, email: request.name, password: request.password)
        apollo.perform(mutation: mut) { [weak self] res, error in
            
            if let error = error {
                showAlert(title: error.localizedDescription) { }
            }
            presentGraph(errors: res?.errors)
        }
    }
    
}
