//
//  RegisterRouter.swift
//  Capo
//
//  Created by Артем Валиев on 12/12/2018.
//  Copyright (c) 2018 Артем Валиев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterRoutingLogic
{
    func routeToLoginController(credentials: Credentials?)
}

protocol RegisterDataPassing
{
  var dataStore: RegisterDataStore? { get }
}

class RegisterRouter: NSObject, RegisterRoutingLogic, RegisterDataPassing
{
  weak var viewController: RegisterViewController?
  var dataStore: RegisterDataStore?
  
    
    func routeToLoginController(credentials: Credentials?) {
        
        if let destinationVC = viewController?.navigationController?.viewControllers.first as? LoginViewController {
            var destinationDS = destinationVC.router!.dataStore!
            if let credentials = credentials {
                destinationDS.registerCredentials = credentials
            }
            viewController?.navigationController?.popViewController(animated: true)
        } else {
            assert(false, "first viewController should be LoginViewController")
        }

        
    }
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: RegisterViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: RegisterDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
