//
//  LoginModels.swift
//  Capo
//
//  Created by Артем Валиев on 12/12/2018.
//  Copyright (c) 2018 Артем Валиев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


struct Credentials {
    let email: String
    let password: String
}

enum Login
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        let credentials: Credentials
    }
    struct Response
    {
        let user: User
    }
    struct ViewModel
    {
        let user: User
    }
  }
}
