//
//  MenuInteractor.swift
//  Capo
//
//  Created by Артем Валиев on 12/12/2018.
//  Copyright (c) 2018 Артем Валиев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MenuBusinessLogic
{
  func doSomething(request: Menu.Something.Request)
}

protocol MenuDataStore
{
  //var name: String { get set }
}

class MenuInteractor: MenuBusinessLogic, MenuDataStore
{
  var presenter: MenuPresentationLogic?
  var worker: MenuWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Menu.Something.Request)
  {
    worker = MenuWorker()
    worker?.doSomeWork()
    
    let response = Menu.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
