//
//  MenuModels.swift
//  Capo
//
//  Created by Артем Валиев on 12/12/2018.
//  Copyright (c) 2018 Артем Валиев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


struct MenuCellVM {
    var text: String
    var isSelected: Bool
    var image: UIImage
    var showDivider: Bool
}

enum MenuObject: Int, CustomStringConvertible, CaseIterable {
    case Profile = 0
    
    var description: String {
        switch self {
        case .Profile:
            return "ПРОФИЛЬ"
        }
    }
    
    var image: UIImage {
        switch self {
        case .Profile:
            return UIImage()
        }
    }
    
    var showDivider: Bool {
        switch self {
        case .Profile:
            return false
        default:
            return true
        }
    }
    
}

enum Menu
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
