//
//  UserProfileModels.swift
//  Capo
//
//  Created by Артем Валиев on 12/12/2018.
//  Copyright (c) 2018 Артем Валиев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UserProfile
{
  // MARK: Use cases
  
  enum FetchUser
  {
    struct Request
    {
    }
    struct Response
    {
        let user: User
    }
    struct ViewModel
    {
        let user: User
    }
  }
    
    enum UpdateUser
    {
        struct Request
        {
            let name: String?
            let userProfileImage: String?
        }
        struct Response
        {
            let user: User
        }
        struct ViewModel
        {
            let user: User
        }
    }
}
