//
//  UserProfileViewController.swift
//  Capo
//
//  Created by Артем Валиев on 12/12/2018.
//  Copyright (c) 2018 Артем Валиев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol UserProfileDisplayLogic: class
{
    func displaySomething(viewModel: UserProfile.Something.ViewModel)
}

class UserProfileViewController: UIViewController, UserProfileDisplayLogic
{
    var interactor: UserProfileBusinessLogic?
    var router: (NSObjectProtocol & UserProfileRoutingLogic & UserProfileDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = UserProfileInteractor()
        let presenter = UserProfilePresenter()
        let router = UserProfileRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    @IBOutlet weak var logoutButton: LGButton!
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        logoutButton.applyLoginSettings(title: "Выйти")
    }
    

    
    func displaySomething(viewModel: UserProfile.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
    
    @IBAction func logoutPressed() {
        CurrentUser.removeData()
        let contr = getController(forName: LoginViewController.self, showMenuButton: false)
        setCenter(controller: contr)
    }
}
